### ISSUE TITLE
URL.canParse is not a function

### ISSUE THREAD

**Issue by ArthurGuez** [fpapado/svg-use#75]
Hello there,

On older browers (Firefox 112 for example) I'm having this issue : "URL.canParse is not a function".

Does that mean that `svg-use` doesn't work on browers that don't support [URL.canParse](https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static)?

Thanks,

**Comment by fpapado** [comment]
Hi @ArthurGuez, thank you for filing this! 

`URL.canParse` is used as a shorthand in the default dev-time-only checks in: https://github.com/fpapado/svg-use/blob/146cd2d69ee308ecb1100d52bce544fa7049e192/packages/react/src/runtimeChecks.dev.tsx#L3

Have you run into this issue in production? **My first recommendation, to unblock you, would be to configure the runtime checks to be dev-only** on your end, such as:

```tsx
import { configContext, type Config } from '@svg-use/react';

const config: Config = {
  // Add any config options here
  rewritePath: (pathOrHref) => pathOrHref,
  runtimeChecksEnabled: process.env.NODE_ENV !== 'production',
};

const AppRoot = () => {
  return (
    <configContext.Provider value={config}>
    {\/* The rest of the application *\/}
    </configContext.Provider>
  );
};
```

That would only use `URL.canParse` during development, with a tacit assumption that development browsers are up to date.

---

However, this prompted me to realise what `runtimeChecksEnabled` defaults to `true` (in order to avoid misconfiguration of the paths, which is a common pitfall with `<use>`), which means that `URL.canParse` can end up in production even if the caller did not intend it. I'll make a small patch update to use it as a progressive enhancement, falling back to `new URL` instead 🔧
